language: php

services:
    - redis-server

matrix:
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4

before_script:
    - composer install --dev
    - cp .env.dist .env

script: ./vendor/bin/phpunit
